dubbo:
  application:
    name: background-service
  registry:
    protocol: zookeeper
    address: 192.168.43.130:2181
  protocol:
    port: 28801

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java-v9
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 970514
